name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./FlagExplorerBackend.csproj
    - name: Build
      run: dotnet build ./FlagExplorerBackend.csproj --configuration Release --no-restore
    - name: Start API in the background
      run: dotnet /home/runner/work/FlagExplorerBackend/FlagExplorerBackend/bin/Release/net8.0/FlagExplorerBackend.dll &
          sleep 10  # Wait for API to start
    - name: Install Newman
      run: npm install -g newman
    - name: Run Postman Tests
      run: newman run Tests/FlagExplorerBackendTests.postman_collection.json --insecure
